[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm_cpi = "8Cf3kqS5x99QsmBUFM27cSedfrBUU1RyG8a5rJayda5A"

[programs.devnet]
amm_cpi = "8Cf3kqS5x99QsmBUFM27cSedfrBUU1RyG8a5rJayda5A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/amitesh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
